steps:
- name: gcr.io/cloud-builders/docker
  args: ["run", "eu.gcr.io/veganbase/service-builder", "./build/run-tests", "social-service"]
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "social-service", "-f", "services/social-service/Dockerfile", "."]
- name: gcr.io/cloud-builders/docker
  args: ["tag", "social-service", "eu.gcr.io/veganbase/social-service:$SHORT_SHA"]

images:
- eu.gcr.io/veganbase/social-service
