// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AddItemBlobs provides a mock function with given fields: itemID, blobIDs
func (_m *Client) AddItemBlobs(itemID string, blobIDs []string) error {
	ret := _m.Called(itemID, blobIDs)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(itemID, blobIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveItemBlobs provides a mock function with given fields: itemID, blobIDs
func (_m *Client) RemoveItemBlobs(itemID string, blobIDs []string) error {
	ret := _m.Called(itemID, blobIDs)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = rf(itemID, blobIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
