development:
    dialect: postgres
    datasource: dbname=vb_social sslmode=disable
    dir: migrations
    table: migrations

production:
    dialect: postgres
    datasource: dbname=vb_social
    dir: migrations
    table: migrations
