INSERT INTO blobs VALUES ('blob0001', 'http://image.com/blob0001.jpg', 'image/jpeg', 24000, 'usr_TESTUSER1', '{"beach":true,"holiday":true}',     now() - INTERVAL '1 minute');
INSERT INTO blobs VALUES ('blob0002', 'http://image.com/blob0002.jpg', 'image/jpeg', 24000, 'usr_TESTUSER2', '{"lunch":true,"cake":true}',        now() - INTERVAL '2 minute');
INSERT INTO blobs VALUES ('blob0003', 'http://image.com/blob0003.jpg', 'image/jpeg', 24000, 'usr_TESTUSER2', '{"lunch":true,"cordon-bleu":true}', now() - INTERVAL '3 minute');
INSERT INTO blobs VALUES ('blob0004', 'http://image.com/blob0004.jpg', 'image/jpeg', 24000, 'usr_TESTUSER3', '{}',                                now() - INTERVAL '4 minute');
INSERT INTO blobs VALUES ('blob0005', 'http://image.com/blob0005.jpg', 'image/jpeg', 24000, 'usr_TESTUSER1', '{}',                                now() - INTERVAL '5 minute');
INSERT INTO blobs VALUES ('blob0006', 'http://image.com/blob0006.jpg', 'image/jpeg', 24000, 'usr_TESTUSER1', '{"beach":true}',                    now() - INTERVAL '6 minute');
INSERT INTO blobs VALUES ('blob0007', 'http://image.com/blob0007.jpg', 'image/jpeg', 24000, 'usr_TESTUSER3', '{"evening":true}',                  now() - INTERVAL '7 minute');
INSERT INTO blobs VALUES ('blob0008', 'http://image.com/blob0008.jpg', 'image/jpeg', 24000, 'usr_TESTUSER2', '{"seaside":true,"shells":true}',    now() - INTERVAL '8 minute');
INSERT INTO blobs VALUES ('blob0009', 'http://image.com/blob0009.jpg', 'image/jpeg', 24000, 'usr_TESTUSER1', '{}',                                now() - INTERVAL '9 minute');
INSERT INTO blobs VALUES ('blob0010', 'http://image.com/blob0010.jpg', 'image/jpeg', 24000, 'usr_TESTUSER1', '{"beach":true}',                    now() - INTERVAL '10 minute');
INSERT INTO blobs VALUES ('blob0011', 'http://image.com/blob0011.jpg', 'image/jpeg', 24000, 'usr_TESTUSER4', '{}',                                now() - INTERVAL '11 minute');
INSERT INTO blobs VALUES ('blob0012', 'http://image.com/blob0012.jpg', 'image/jpeg', 24000, 'usr_TESTUSER4', '{}',                                now() - INTERVAL '12 minute');
INSERT INTO blobs VALUES ('blob0013', 'http://image.com/blob0013.jpg', 'image/jpeg', 24000, NULL,            '{}',                                now() - INTERVAL '12 minute');
INSERT INTO blobs VALUES ('blob0014', 'http://image.com/blob0014.jpg', 'image/jpeg', 24000, NULL,            '{}',                                now() - INTERVAL '12 minute');
INSERT INTO blobs VALUES ('blob0015', 'http://image.com/blob0015.jpg', 'image/jpeg', 24000, NULL,            '{}',                                now() - INTERVAL '13 minute');
INSERT INTO blob_items (blob_id, item_id) VALUES ('blob0001', 'item0001');
INSERT INTO blob_items (blob_id, item_id) VALUES ('blob0001', 'item0002');
INSERT INTO blob_items (blob_id, item_id) VALUES ('blob0002', 'item0003');
INSERT INTO blob_items (blob_id, item_id) VALUES ('blob0013', 'item0023');
INSERT INTO blob_items (blob_id, item_id) VALUES ('blob0013', 'item0025');
INSERT INTO blob_items (blob_id, item_id) VALUES ('blob0013', 'item0026');
INSERT INTO blob_items (blob_id, item_id) VALUES ('blob0014', 'item0080');
INSERT INTO blob_items (blob_id, item_id) VALUES ('blob0015', 'item0080');
