// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id, format
func (_m *Storage) Delete(id string, format string) error {
	ret := _m.Called(id, format)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, format)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Write provides a mock function with given fields: id, format, data
func (_m *Storage) Write(id string, format string, data []byte) (string, int64, error) {
	ret := _m.Called(id, format, data)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, []byte) string); ok {
		r0 = rf(id, format, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(string, string, []byte) int64); ok {
		r1 = rf(id, format, data)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, []byte) error); ok {
		r2 = rf(id, format, data)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
