// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/veganbase/backend/services/site-service/model"

// DB is an autogenerated mock type for the DB type
type DB struct {
	mock.Mock
}

// SaveEvent provides a mock function with given fields: label, eventData, inTx
func (_m *DB) SaveEvent(label string, eventData interface{}, inTx func() error) error {
	ret := _m.Called(label, eventData, inTx)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, func() error) error); ok {
		r0 = rf(label, eventData, inTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Sites provides a mock function with given fields:
func (_m *DB) Sites() (map[string]*model.Site, error) {
	ret := _m.Called()

	var r0 map[string]*model.Site
	if rf, ok := ret.Get(0).(func() map[string]*model.Site); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*model.Site)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
