steps:
- name: gcr.io/cloud-builders/docker
  args: ["run", "eu.gcr.io/veganbase/service-builder", "./build/run-tests", "email-service"]
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "email-service", "-f", "services/email-service/Dockerfile", "."]
- name: gcr.io/cloud-builders/docker
  args: ["tag", "email-service", "eu.gcr.io/veganbase/email-service:$SHORT_SHA"]

images:
- "eu.gcr.io/veganbase/email-service"
