// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import events "github.com/veganbase/backend/services/category-service/events"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Categories provides a mock function with given fields:
func (_m *Client) Categories() events.CategoryMap {
	ret := _m.Called()

	var r0 events.CategoryMap
	if rf, ok := ret.Get(0).(func() events.CategoryMap); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(events.CategoryMap)
		}
	}

	return r0
}

// IsValidLabel provides a mock function with given fields: catName, label
func (_m *Client) IsValidLabel(catName string, label string) bool {
	ret := _m.Called(catName, label)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(catName, label)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
