steps:
- name: gcr.io/cloud-builders/docker
  args: ["run", "eu.gcr.io/veganbase/service-builder", "./build/run-tests", "blob-service"]
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "blob-service", "-f", "services/blob-service/Dockerfile", "."]
- name: gcr.io/cloud-builders/docker
  args: ["tag", "blob-service", "eu.gcr.io/veganbase/blob-service:$SHORT_SHA"]

images:
- "eu.gcr.io/veganbase/blob-service"
